import { SalesInvoice, SalesInvoiceLine, SalesInvoiceDiscountType, SalesInvoiceStatus, SalesPayment } from '../../../../shared/models/sales';

export function mapRowToSalesInvoice(row: any): SalesInvoice {
  return {
    id: row.id,
    shopId: row.shopId,
    customerId: row.customerId,
    draftReference: row.draftReference,
    invoiceNumber: row.invoiceNumber || null,
    invoiceDate: row.invoiceDate,
    dueDate: row.dueDate || null,
    status: row.status as SalesInvoiceStatus,
    paymentStatus: row.paymentStatus as any,
    salesChannel: row.salesChannel as any,
    subtotal: row.subtotal ?? 0,
    lineDiscountTotal: row.lineDiscountTotal ?? 0,
    invoiceDiscountType: (row.invoiceDiscountType || 'NONE') as SalesInvoiceDiscountType,
    invoiceDiscountValue: row.invoiceDiscountValue ?? 0,
    invoiceDiscountTotal: row.invoiceDiscountTotal ?? 0,
    taxableAmount: row.taxableAmount ?? 0,
    cgstTotal: row.cgstTotal ?? 0,
    sgstTotal: row.sgstTotal ?? 0,
    igstTotal: row.igstTotal ?? 0,
    cessTotal: row.cessTotal ?? 0,
    roundOff: row.roundOff ?? 0,
    grandTotal: row.grandTotal ?? 0,
    paidAmount: row.paidAmount ?? 0,
    outstandingAmount: row.outstandingAmount ?? 0,
    changeAmount: row.changeAmount ?? 0,
    notes: row.notes || null,
    heldAt: row.heldAt || null,
    postedAt: row.postedAt || null,
    cancelledAt: row.cancelledAt || null,
    cancellationReason: row.cancellationReason || null,
    createdAt: row.createdAt,
    updatedAt: row.updatedAt,
    version: row.version ?? 1,
  };
}

export function mapRowToSalesInvoiceLine(row: any): SalesInvoiceLine {
  return {
    id: row.id,
    salesInvoiceId: row.salesInvoiceId,
    productId: row.productId,
    productCodeSnapshot: row.productCodeSnapshot,
    productNameSnapshot: row.productNameSnapshot,
    barcodeSnapshot: row.barcodeSnapshot || null,
    hsnSacCodeSnapshot: row.hsnSacCodeSnapshot || null,
    productTypeSnapshot: row.productTypeSnapshot as any,
    unitId: row.unitId || null,
    unitNameSnapshot: row.unitNameSnapshot || null,
    taxRateId: row.taxRateId || null,
    taxCategorySnapshot: row.taxCategorySnapshot as any,
    taxRateSnapshot: row.taxRateSnapshot ?? 0,
    quantity: row.quantity ?? 0,
    unitPrice: row.unitPrice ?? 0,
    mrp: row.mrp ?? 0,
    minimumSellingPrice: row.minimumSellingPrice || null,
    discountType: (row.discountType || 'NONE') as any,
    discountValue: row.discountValue ?? 0,
    discountAmount: row.discountAmount ?? 0,
    invoiceDiscountAllocation: row.invoiceDiscountAllocation ?? 0,
    taxableAmount: row.taxableAmount ?? 0,
    cgstRate: row.cgstRate ?? 0,
    cgstAmount: row.cgstAmount ?? 0,
    sgstRate: row.sgstRate ?? 0,
    sgstAmount: row.sgstAmount ?? 0,
    igstRate: row.igstRate ?? 0,
    igstAmount: row.igstAmount ?? 0,
    cessRate: row.cessRate ?? 0,
    cessAmount: row.cessAmount ?? 0,
    lineTotal: row.lineTotal ?? 0,
    inventoryTransactionId: row.inventoryTransactionId || null,
    createdAt: row.createdAt,
    updatedAt: row.updatedAt,
  };
}

export function mapRowToSalesPayment(row: any): SalesPayment {
  return {
    id: row.id,
    salesInvoiceId: row.salesInvoiceId,
    paymentMode: row.paymentMode as any,
    amount: Number(row.amount || 0),
    referenceNumber: row.referenceNumber || null,
    paymentDate: row.paymentDate,
    status: row.status as any,
    notes: row.notes || null,
    idempotencyKey: row.idempotencyKey || null,
    createdAt: row.createdAt,
    paymentSource: row.paymentSource as any
  };
}
